title: "Caleb"
tagline: "Data Analyst"
description: "Portfolio showcasing data analytics, visualisation, and insights work."
url: "https://shazilazi.github.io"
baseurl: ""

author:
  name: "Caleb"
  role: "Data Analyst"
  bio: "I turn messy data into clear decisions."
  company: "Frontline Research Group"
  location: "Port Elizabeth, South Africa"
  linkedin: "https://www.linkedin.com/in/caleb-trent-aa6ba915a/"
  github: "https://github.com/Shazilazi"
  email: "caleb.trent93@gmail.com"

include:
  - _pages

collections:
  projects:
    output: true
    permalink: /projects/:name/

defaults:
  - scope:
      path: "_pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

markdown: kramdown
plugins:
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
